services:
  web:
    build: .
    container_name: escola-da-fe-web
    ports:
      - "8081:80"
    environment:
      APP_ENV: development
      BASE_URL: /
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
