services:
  web:
    image: ${IMAGE_NAME:-escola-da-fe:latest}
    build:
      context: .
    ports:
      - "${HTTP_PORT:-80}:80"
    environment:
      APP_ENV: production
      BASE_URL: ${BASE_URL:-/}
    restart: always
